[package]
name = "elixir"
version = "0.1.0"
edition = "2018"

[dependencies]
rocket = "0.5.0-rc.1"
sailfish = { git = "https://github.com/knarkzel/sailfish" }
libsqlite3-sys = { version = "0.12.0", features = ["bundled"] }

[dependencies.rocket_sync_db_pools]
version = "0.1.0-rc.1"
features = ["diesel_sqlite_pool"]
